server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microhotel
    username: root


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: HOTEL-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

